[package]
name = "chanakya-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "chanakya"
path = "src/main.rs"

[dependencies]
chanakya-model = { workspace = true }
chanakya-io = { workspace = true }
chanakya-scaling = { workspace = true }
chanakya-presolve = { workspace = true }
chanakya-linalg = { workspace = true }
chanakya-lp = { workspace = true }
chanakya-ipm = { workspace = true }
chanakya-qp = { workspace = true }
chanakya-mip = { workspace = true }
chanakya-verify = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
