[package]
name = "chanakya-qp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chanakya-model = { workspace = true }
chanakya-linalg = { workspace = true }
chanakya-ipm = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
